CREATE TABLE ACCOUNT_TYPE (
    Account_Type_ID NUMBER(15) CONSTRAINT PK_ACCOUNT PRIMARY KEY NOT NULL,
    Mnemonic VARCHAR(50) NOT NULL UNIQUE,
    Account_Type_Name VARCHAR(50) NOT NULL,
    Creation_Date DATE NOT NULL
);

CREATE TABLE ACCOUNT_TRANSACTION (
     Account_TX_ID NUMBER(15) CONSTRAINT PK_TRANSACT PRIMARY KEY NOT NULL,
     Account_Type_ID NUMBER(15) NOT NULL,
     Member_ID NUMBER(15) NOT NULL,
     Amount INT NOT NULL,
     TX_Date DATE NOT NULL,
     CONSTRAINT FK_ACCOUNT FOREIGN KEY (Account_Type_ID) REFERENCES ACCOUNT_TYPE(Account_Type_ID)
);

CREATE TABLE MEMBER_ACCOUNT (
     Member_Account_ID NUMBER(15) CONSTRAINT PK_MEMBER PRIMARY KEY NOT NULL,
     Member_ID NUMBER(15) NOT NULL,
     Account_Type_ID NUMBER(15) NOT NULL,
     Balance INT NOT NULL,
     Created_Date DATE NOT NULL,
     CONSTRAINT FK_ACCOUNT_TRANSACT FOREIGN KEY (Account_Type_ID) REFERENCES ACCOUNT_TYPE(Account_Type_ID)
);

CREATE SEQUENCE HR.ACC_MEMBER_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE HR.ACC_TX_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE HR.ACC_TYPE_SEQ
START WITH 1
INCREMENT BY 1;
 
DROP TABLE ACCOUNT_TRANSACTION CASCADE CONSTRAINTS;
DROP TABLE ACCOUNT_TYPE CASCADE CONSTRAINTS;
DROP TABLE MEMBER_ACCOUNT CASCADE CONSTRAINTS;